const domainName = 'https://abdellatif-laghjaj.000webhostapp.com/';

const PROJECTS_DATA = [
    {
        id: 1,
        title: 'URL Shortener',
        description: 'Simple URL Shortener that allows you to shorten your URL and get a short link.',
        image: 'assets/online_tech_store.png',
        link: 'https://github.com/abdellatif-laghjaj/url-shortener',
        preview: 'url-shortener/',
        tech: ['HTML', 'CSS', 'JS', 'PHP', 'MySQL', 'NodeJS'],
        isPopular: true,
    },
    {
        id: 2,
        title: 'Weather Web App',
        description: 'Simple Weather Web App that allows you to get the weather of any city.',
        image: 'assets/online_tech_store.png',
        link: 'https://github.com/abdellatif-laghjaj/weather-web-app',
        preview: domainName + 'weather-web-app/',
        tech: ['HTML', 'CSS', 'JS'],
        isPopular: true,
    },
    {
        id: 3,
        title: 'Quotes Generator',
        description: 'Simple Quotes Generator that allows you to get a random quote.',
        image: 'assets/online_tech_store.png',
        link: 'https://github.com/abdellatif-laghjaj/quotes-generator',
        preview: domainName + 'quotes-generator/',
        tech: ['HTML', 'CSS', 'JS'],
        isPopular: false,
    },
    {
        id: 4,
        title: 'Online Tech Store',
        description: 'Simple Online Tech Store that allows you to buy electronic prodcuts with admin panel.',
        image: 'assets/online_tech_store.png',
        link: 'https://github.com/abdellatif-laghjaj/Ivenontory-managment-system',
        preview: 'https://github.com/abdellatif-laghjaj/Ivenontory-managment-system',
        tech: ['HTML', 'CSS', 'JS', 'Bootstrap', 'PHP', 'MySQL'],
        isPopular: true,
    },
    {
        id: 5,
        title: 'YouTube Video Downloader',
        description: 'Simple YouTube Video Downloader that allows you to download any video from YouTube and also the thumbnail of the video.',
        image: 'assets/online_tech_store.png',
        link: 'https://github.com/abdellatif-laghjaj/youtube_video_downloader',
        preview: domainName + 'youtube_video_downloader/',
        tech: ['HTML', 'CSS', 'JS', 'PHP'],
        isPopular: true,
    },
    {
        id: 6,
        title: 'Portfolio',
        description: 'Simple and clean Portfolio for my personal projects.',
        image: 'assets/online_tech_store.png',
        link: 'https://github.com/abdellatif-laghjaj/portfolio',
        preview: domainName + 'portfolio/',
        tech: ['HTML', 'CSS', 'JS'],
        isPopular: true,
    },
    {
        id: 7,
        title: 'Music Player',
        description: 'Simple Music Player that allows you to play your local music from your computer.',
        image: 'assets/online_tech_store.png',
        link: 'https://github.com/abdellatif-laghjaj/Music-Player',
        preview: 'https://github.com/abdellatif-laghjaj/Music-Player',
        tech: ['C#', 'WPF', 'Windows Media Player'],
    },
    {
        id: 8,
        title: 'Personal Expenses Tracker',
        description: 'Simple Personal Expenses Tracker that allows you to track your expenses.',
        image: 'assets/online_tech_store.png',
        link: 'https://github.com/abdellatif-laghjaj/personal_expenses_app',
        preview: 'https://github.com/abdellatif-laghjaj/personal_expenses_app',
        tech: ['DART', 'Flutter'],
        isPopular: false,
    },
    {
        id: 9,
        title: 'Android all in one video downloader',
        description: 'Simple Android all in one video downloader that allows you to download any video from YouTube and also the thumbnail of the video.',
        image: 'assets/online_tech_store.png',
        link: 'https://github.com/abdellatif-laghjaj/android-all-in-one-video-downloader',
        preview: 'https://github.com/abdellatif-laghjaj/android-all-in-one-video-downloader',
        tech: ['JAVA', 'Android-dl'],
        isPopular: false,
    },
    {
        id: 10,
        title: 'Flutter Meals App',
        description: 'Simple Static Flutter Meals App that fetch static meals data',
        image: 'assets/online_tech_store.png',
        link: 'https://github.com/abdellatif-laghjaj/flutter_meals_app',
        preview: 'https://github.com/abdellatif-laghjaj/flutter_meals_app',
        tech: ['DART', 'Flutter'],
        isPopular: false,
    }
];